### Tiny data for tests only
tiny_h5:
    data_root: ../../data/
    data_format: h5
    train_data: ../../data/tiny_h5/train.h5
    valid_data: ../../data/tiny_h5/valid.h5
    test_data: ../../data/tiny_h5/test.h5

frappe_x1:
    data_format: csv
    data_root: ../../data/
    feature_cols:
        - active: true
          dtype: float
          name: [ user, item, daytime, weekday, isweekend, homework, cost, weather, country,
                  city ]
          type: categorical
    label_col: { dtype: float, name: label }
    min_categr_count: 1
    test_data: ../../data/frappe_x1/test.csv
    train_data: ../../data/frappe_x1/train.csv
    valid_data: ../../data/frappe_x1/valid.csv

ipinyou_x1:
    data_format: csv
    data_root: ../../data/
    feature_cols:
        - active: true
          dtype: float
          name: [ weekday, hour, IP, region, city, adexchange, domain, slotid, slotwidth, slotheight,
                  slotvisibility, slotformat, creative, advertiser, useragent, slotprice]
          type: categorical
    label_col: { dtype: float, name: click }
    min_categr_count: 1
    test_data: ../../data/ipinyou_x1/test.csv
    train_data: ../../data/ipinyou_x1/train.csv
    valid_data: ../../data/ipinyou_x1/test.csv

kkbox_x1:
    data_format: csv
    data_root: ../../data/
    feature_cols:
    -   active: true
        dtype: str
        name: [msno, song_id, source_system_tab, source_screen_name, source_type,
            city, gender, registered_via, language]
        type: categorical
    - {active: true, dtype: str, encoder: MaskedSumPooling, max_len: 3, name: genre_ids,
        type: sequence}
    - {active: true, dtype: str, encoder: MaskedSumPooling, max_len: 3, name: artist_name,
        type: sequence}
    - {active: true, dtype: str, name: isrc, preprocess: extract_country_code, type: categorical}
    - {active: true, dtype: str, name: bd, preprocess: bucketize_age, type: categorical}
    label_col: {dtype: float, name: label}
    min_categr_count: 10
    test_data: ../../data/KKBox_x1/test.csv
    train_data: ../../data/KKBox_x1/train.csv
    valid_data: ../../data/KKBox_x1/valid.csv
    spe_processor: kkbox

avazu_x6:
    data_format: csv
    data_root: ../../data/
    feature_cols:
        - { active: false, dtype: str, name: id, type: categorical }
        - { active: true, dtype: str, name: hour, preprocess: convert_hour, type: categorical }
        - active: true
          dtype: str
          name: [ C1, banner_pos, site_id, site_domain, site_category, app_id, app_domain,
                  app_category, device_id, device_ip, device_model, device_type, device_conn_type,
                  C14, C15, C16, C17, C18, C19, C20, C21 ]
          type: categorical
        - { active: true, dtype: str, name: weekday, preprocess: convert_weekday, type: categorical }
        - { active: true, dtype: str, name: weekend, preprocess: convert_weekend, type: categorical }
    label_col: { dtype: float, name: click }
    min_categr_count: 1
    test_data: ../../data/avazu_x4/test.csv
    train_data: ../../data/avazu_x4/train.csv
    valid_data: ../../data/avazu_x4/valid.csv
    spe_processor: avazu