### Tiny data for tests only
tiny_h5:
    data_root: ../../../data/
    data_format: h5
    train_data: ../../../data/tiny_h5/train.h5
    valid_data: ../../../data/tiny_h5/valid.h5
    test_data: ../../../data/tiny_h5/test.h5

ipinyou_x1:
    data_format: csv
    data_root: ../../../data/
    feature_cols:
        - active: true
          dtype: float
          name: [ weekday, hour, IP, region, city, adexchange, domain, slotid, slotwidth, slotheight,
                  slotvisibility, slotformat, creative, advertiser, useragent, slotprice]
          type: categorical
    label_col: { dtype: float, name: click }
    min_categr_count: 1
    test_data: ../../../data/ipinyou_x1/test.csv
    train_data: ../../../data/ipinyou_x1/train.csv
    valid_data: ../../../data/ipinyou_x1/test.csv

taobaoad_x1:
    data_root: ../../../data/
    data_format: csv
    train_data: ../../../data/TaobaoAd_x1/train.csv
    valid_data: ../../../data/TaobaoAd_x1/test.csv
    test_data: ../../../data/TaobaoAd_x1/test.csv
    min_categr_count: 10
    feature_cols:
        - {name: "group_id", active: True, dtype: int, type: meta, preprocess: "copy_from(userid)", remap: False}
        - {name: ["userid","cms_segid","cms_group_id","final_gender_code","age_level","pvalue_level","shopping_level",
                  "occupation","new_user_class_level","adgroup_id","cate_id","campaign_id","customer","brand","pid","btag"],
                  active: True, dtype: str, type: categorical}
        - {name: price, active: True, dtype: float, type: numeric}
        - {name: cate_his, active: True, dtype: str, splitter: ^, type: sequence, max_len: 50, padding: pre,
           share_embedding: cate_id}
        - {name: brand_his, active: True, dtype: str, splitter: ^, type: sequence, max_len: 50, padding: pre,
           share_embedding: brand}
        - {name: btag_his, active: True, dtype: str, splitter: ^, type: sequence, max_len: 50, padding: pre,
           share_embedding: btag}
    label_col: {name: clk, dtype: float}

movielens:
    data_format: csv
    data_root: ../../../data/
    feature_cols:
        - active: true
          dtype: float
          name: [user_id, movie_id, timestamp, title, genres, gender, age, occupation, zip]
          type: categorical
    label_col: { dtype: float, name: click }
    min_categr_count: 1
    test_data: ../../../data/movielens/test.csv
    train_data: ../../../data/movielens/train.csv
    valid_data: ../../../data/movielens/valid.csv

kkbox_x1:
    data_format: csv
    data_root: ../../../data/
    feature_cols:
    -   active: true
        dtype: str
        name: [msno, song_id, source_system_tab, source_screen_name, source_type,
            city, gender, registered_via, language]
        type: categorical
    - {active: true, dtype: str, encoder: MaskedSumPooling, max_len: 3, name: genre_ids,
        type: sequence}
    - {active: true, dtype: str, encoder: MaskedSumPooling, max_len: 3, name: artist_name,
        type: sequence}
    - {active: true, dtype: str, name: isrc, preprocess: extract_country_code, type: categorical}
    - {active: true, dtype: str, name: bd, preprocess: bucketize_age, type: categorical}
    label_col: {dtype: float, name: label}
    min_categr_count: 10
    test_data: ../../../data/KKBox_x1/test.csv
    train_data: ../../../data/KKBox_x1/train.csv
    valid_data: ../../../data/KKBox_x1/valid.csv
    spe_processor: kkbox

criteo_x6:
    feature_cols:
        - { name: [ I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11,I12,I13 ],
            active: True, dtype: float, type: categorical, preprocess: convert_to_bucket, fill_na: 0 }
        - { name: [ C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,C15,C16,C17,C18,C19,C20,C21,C22,C23,C24,C25,C26 ],
            active: True, dtype: str, type: categorical, fill_na: "" }
    label_col: {dtype: float, name: Label}
    min_categr_count: 10
    data_root: ../../../data/
    data_format: csv
    train_data: ../../../data/criteo_x4/train.csv
    valid_data: ../../../data/criteo_x4/valid.csv
    test_data: ../../../data/criteo_x4/test.csv
    spe_processor: criteo

avazu_x4:
    data_format: csv
    data_root: ../../../data/
    feature_cols:
        - { active: false, dtype: str, name: id, type: categorical }
        - { active: true, dtype: str, name: hour, preprocess: convert_hour, type: categorical }
        - active: true
          dtype: str
          name: [ C1, banner_pos, site_id, site_domain, site_category, app_id, app_domain,
                  app_category, device_id, device_ip, device_model, device_type, device_conn_type,
                  C14, C15, C16, C17, C18, C19, C20, C21 ]
          type: categorical
        - { active: true, dtype: str, name: weekday, preprocess: convert_weekday, type: categorical }
        - { active: true, dtype: str, name: weekend, preprocess: convert_weekend, type: categorical }
    label_col: { dtype: float, name: click }
    min_categr_count: 2
    test_data: ../../../data/avazu_x4/test.csv
    train_data: ../../../data/avazu_x4/train.csv
    valid_data: ../../../data/avazu_x4/valid.csv
    spe_processor: avazu

frappe_x1:
    data_format: csv
    data_root: ../../../data/
    feature_cols:
        - active: true
          dtype: float
          name: [ user, item, daytime, weekday, isweekend, homework, cost, weather, country,
                  city ]
          type: categorical
    label_col: { dtype: float, name: label }
    min_categr_count: 1
    test_data: ../../../data/frappe_x1/test.csv
    train_data: ../../../data/frappe_x1/train.csv
    valid_data: ../../../data/frappe_x1/valid.csv

ipinyou_x2:
    data_format: csv
    data_root: ../../../data/
    feature_cols:
    -   active: true
        dtype: str
        name: [weekday,hour,IP,region,city,adexchange,domain,
               slotid,slotwidth,slotheight,slotvisibility,slotformat,
               creative,advertiser,useragent,slotprice]
        type: categorical
    label_col: { dtype: float, name: click }
    min_categr_count: 2
    train_data: ../../../data/ipinyou_x2/train.csv
    valid_data: ../../../data/ipinyou_x2/valid.csv
    test_data: ../../../data/ipinyou_x2/test.csv

avazu_x6:
    data_format: csv
    data_root: ../../../data/
    feature_cols:
        - { active: false, dtype: str, name: id, type: categorical }
        - { active: true, dtype: str, name: hour, preprocess: convert_hour, type: categorical }
        - active: true
          dtype: str
          name: [ C1, banner_pos, site_id, site_domain, site_category, app_id, app_domain,
                  app_category, device_id, device_ip, device_model, device_type, device_conn_type,
                  C14, C15, C16, C17, C18, C19, C20, C21 ]
          type: categorical
        - { active: true, dtype: str, name: weekday, preprocess: convert_weekday, type: categorical }
        - { active: true, dtype: str, name: weekend, preprocess: convert_weekend, type: categorical }
    label_col: { dtype: float, name: click }
    min_categr_count: 1
    test_data: ../../../data/avazu_x4/test.csv
    train_data: ../../../data/avazu_x4/train.csv
    valid_data: ../../../data/avazu_x4/valid.csv
    spe_processor: avazu