DCN_re_frappe:
    model: DCN
    dataset_id: frappe_x1
    loss: 'binary_crossentropy'
    metrics: [ 'logloss', 'AUC' ]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0 #.05
    weight_decay: 5.0e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    dnn_hidden_units: [ 400, 400, 400 ]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0.2
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 20242025
    monitor: { 'AUC': 1, 'logloss': -1 }
    monitor_mode: 'max'
    crossing_layers: 3
    num_workers: 3
    method: 'tayfcs'
    mode: 'lre_hash'
    paths: # automating redirect to the correct path
        score_path: 2
        ele_path: 3

DCN_re_ipinyou:
    dataset_id: ipinyou_x2
    batch_size: 10000
    crossing_layers: 3
    dnn_activations: relu
    dnn_hidden_units: [1000, 1000]
    embedding_dim: 16
    weight_decay: 5.0e-8
    embedding_dropout: 0
    embedding_regularizer: 1.0e-3
    epochs: 100
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_hdf5: true
    workers: 3
    method: 'tayfcs'
    mode: 'lre_hash'
    paths: # automating redirect to the correct path
        score_path: ""
        ele_path: 2

DCN_re_avazu:
    dataset_id: avazu_x6
    batch_size: 10000
    crossing_layers: 3
    dnn_activations: relu
    dnn_hidden_units: [1000, 1000]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_hdf5: true
    workers: 3
    method: 'tayfcs'
    mode: 'lre_hash'
    paths: # automating redirect to the correct path
        score_path: ""
        ele_path: 2